<x-app-layout>
    <x-slot name="header">
        <div class="flex justify-between">
            <h2 class="font-semibold text-xl text-gray-800 leading-tight">
                {{ __('Posts') }}
            </h2>
            <a href="{{route('posts.create')}}" class="rounded-md bg-sky-500 px-3.5 py-2.5 text-sm font-semibold text-white shadow-xs  hover:bg-sky-700 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-sky-500">Create Post</a>
        </div>
    </x-slot>


    <div class="mt-2 mb-2 px-2 py-2">
            {{ $posts->onEachSide(5)->links() }}

    </div>

    <table class="min-w-full divide-y divide-gray-200 py-12">
        <thead class="bg-gray-50">
        <tr>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">ID</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Title
            </th>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Description</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Author</th>
            <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>
        </tr>
        </thead>
        <tbody class="bg-white divide-y divide-gray-200">
        @if(!is_null($posts))
        @foreach ($posts as $post)
            <tr>
                <td class="px-6 py-4 whitespace-nowrap">{{ $post->id }}</td>

                <td class="px-6 py-4 whitespace-nowrap font-medium">
                    {{ $post->title }}
                </td>

                <td class="px-6 py-4">
                    <span class="text-gray-700">
                        {{ Str::limit($post->description, 60) }}
                    </span>
                </td>

                <td class="px-6 py-4 whitespace-nowrap">
                    {{ $post->user->name }}
                </td>

                <td class="px-6 py-4 whitespace-nowrap space-x-3">
                    <a href="{{route('posts.show', $post->id)}}"  class="text-green-600 hover:text-green-800">show</a>

                    @canany(['update','delete'], $post)

                        <a href="#" onclick="editPost({{ $post->id }})" class="text-blue-600 hover:text-blue-800">Edit</a>

                        <form action="{{ route('posts.destroy', $post) }}" method="POST" class="inline-block">
                            @csrf
                            @method('DELETE')
                            <button type="submit"
                                    onclick="return confirm('Are you sure?')"
                                    class="text-red-600 hover:text-red-800">
                                Delete
                            </button>
                        </form>
                    @endcanany
                </td>
            </tr>
        @endforeach
        @endif
        </tbody>
    </table>

    <x-modal name="editPostModal" maxWidth="xl">
        <h2 class="text-xl font-bold mb-4 mt-2 text-center">Edit Post</h2>

        <form id="edit-form" method="POST" class="container flex flex-col w-full px-10 py-10">
            @csrf
            @method('PUT')
            <div class="mt-2 w-full">

            <input id="edit-title"
                   name="title"
                   class="block w-38 mb-3 rounded-md w-80"
                   placeholder="Title">
            </div>


            <div class="w-full">
                <textarea id="edit-content"
                          name="description"
                          class="block rounded-md border w-full h-24"
                          placeholder="Content" row="5">
                </textarea>
            </div>


            <div class="mt-5 mb-2 mx-auto">
                <button type="submit" class="bg-sky-500 text-white px-32 py-2 rounded-md hover:bg-sky-700">
                    Save
                </button>

            </div>

        </form>
    </x-modal>

    <script>
        // Route template generated by Laravel
        {{--const updateUrlTemplate = "{{ route('posts.update', ':id') }}";--}}

        function editPost(id) {

            // Fetch post data
            fetch(`posts/${id}/edit`)
                .then(res => res.json())
                .then(post => {

                    // Fill inputs
                    document.getElementById('edit-title').value = post.title;
                    document.getElementById('edit-content').value = post.description;

                    // Replace :id in URL template with real ID
                    // let updateUrl = updateUrlTemplate.replace(':id', id);

                    // Set form action
                    document.getElementById('edit-form').action = `posts/${id}`

                    // Open modal
                    window.dispatchEvent(new CustomEvent('open-modal', { detail: 'editPostModal' }));
                });
        }
    </script>
</x-app-layout>
